//! GLM Local Proxy
//!
//! Converts standard OpenAI Chat Completions API format (as generated by rig-core)
//! into the format accepted by 智谱 AI domestic API (open.bigmodel.cn).
//!
//! Incompatibilities handled:
//! - content array → plain string (GLM requires string, not [{type,text},...])
//! - tool schema: removes anyOf/oneOf/allOf, additionalProperties, examples
//! - tool schema: normalizes ["string","null"] type arrays → "string"
//! - tool schema: adds default "string" type for properties missing a type field
//!
//! Usage:
//!   ZAI_API_KEY=your_key GLM_BASE_URL=https://open.bigmodel.cn/api/paas/v4 glm-local-proxy
//!
//! Then configure IronClaw:
//!   LLM_BACKEND=openai_compatible
//!   LLM_BASE_URL=http://127.0.0.1:4000/v1
//!   LLM_API_KEY=any
//!   LLM_MODEL=glm-5

use axum::{Json, Router, extract::State, http::StatusCode, routing::post};
use serde_json::{Value, json};
use std::sync::Arc;

#[derive(Clone)]
struct AppState {
    client: reqwest::Client,
    glm_base_url: String,
    api_key: String,
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            std::env::var("RUST_LOG")
                .unwrap_or_else(|_| "glm_local_proxy=debug".to_string()),
        )
        .init();

    let api_key = std::env::var("ZAI_API_KEY")
        .expect("ZAI_API_KEY environment variable is required");

    let glm_base_url = std::env::var("GLM_BASE_URL")
        .unwrap_or_else(|_| "https://open.bigmodel.cn/api/paas/v4".to_string());

    let listen_addr = std::env::var("PROXY_ADDR")
        .unwrap_or_else(|_| "127.0.0.1:4000".to_string());

    let state = Arc::new(AppState {
        client: reqwest::Client::new(),
        glm_base_url: glm_base_url.trim_end_matches('/').to_string(),
        api_key,
    });

    let app = Router::new()
        .route("/v1/chat/completions", post(chat_completions))
        .with_state(state);

    tracing::info!("glm-local-proxy listening on http://{}", listen_addr);

    let listener = tokio::net::TcpListener::bind(&listen_addr)
        .await
        .expect("Failed to bind");

    axum::serve(listener, app).await.expect("Server error");
}

async fn chat_completions(
    State(state): State<Arc<AppState>>,
    Json(mut body): Json<Value>,
) -> Result<Json<Value>, (StatusCode, Json<Value>)> {
    tracing::debug!(
        model = body["model"].as_str().unwrap_or("unknown"),
        num_messages = body["messages"].as_array().map(|a| a.len()).unwrap_or(0),
        num_tools = body["tools"].as_array().map(|a| a.len()).unwrap_or(0),
        "Incoming request"
    );

    // Fix messages: flatten content arrays to strings
    if let Some(messages) = body["messages"].as_array_mut() {
        for msg in messages {
            flatten_content(msg);
        }
    }

    // Round temperature to avoid floating-point noise (e.g. 0.6999999999 → 0.7)
    // GLM domestic API returns error 1210 on such values.
    if let Some(t) = body.get("temperature").and_then(|v| v.as_f64()) {
        let rounded = (t * 100.0).round() / 100.0;
        body["temperature"] = json!(rounded);
    }

    // Fix tool schemas: remove unsupported JSON Schema keywords
    if let Some(tools) = body["tools"].as_array_mut() {
        for tool in tools {
            if let Some(params) = tool.pointer_mut("/function/parameters") {
                sanitize_schema(params);
            }
        }
    }

    tracing::trace!(body = %body, "Sanitized request body");

    let url = format!("{}/chat/completions", state.glm_base_url);

    tracing::debug!(%url, "Forwarding to GLM");

    let resp = state
        .client
        .post(&url)
        .bearer_auth(&state.api_key)
        .json(&body)
        .send()
        .await
        .map_err(|e| {
            tracing::error!(error = %e, "Request to GLM failed");
            (
                StatusCode::BAD_GATEWAY,
                Json(json!({"error": {"message": e.to_string(), "type": "proxy_error"}})),
            )
        })?;

    let status = resp.status();
    let glm_body: Value = resp.json().await.map_err(|e| {
        (
            StatusCode::BAD_GATEWAY,
            Json(json!({"error": {"message": e.to_string(), "type": "proxy_error"}})),
        )
    })?;

    if !status.is_success() {
        tracing::warn!(
            status = status.as_u16(),
            error = ?glm_body,
            "GLM returned error"
        );
        return Err((
            StatusCode::from_u16(status.as_u16()).unwrap_or(StatusCode::BAD_GATEWAY),
            Json(glm_body),
        ));
    }

    Ok(Json(glm_body))
}

/// Flatten OpenAI content array to a plain string.
///
/// Converts `[{"type":"text","text":"hello"}]` → `"hello"`.
/// Leaves string content unchanged.
fn flatten_content(msg: &mut Value) {
    if let Some(arr) = msg.get("content").and_then(|c| c.as_array()).cloned() {
        let text: String = arr
            .iter()
            .filter_map(|part| part.get("text").and_then(|t| t.as_str()))
            .collect::<Vec<_>>()
            .join("\n");
        msg["content"] = json!(text);
    }
}

/// Sanitize a JSON Schema for GLM compatibility.
///
/// Removes: anyOf, oneOf, allOf, additionalProperties, examples.
/// Normalizes: ["string","null"] → "string".
/// Adds: default "string" type for properties missing a type.
fn sanitize_schema(schema: &mut Value) {
    let obj = match schema.as_object_mut() {
        Some(o) => o,
        None => return,
    };

    obj.remove("anyOf");
    obj.remove("oneOf");
    obj.remove("allOf");
    obj.remove("additionalProperties");
    obj.remove("examples");

    // ["string", "null"] → "string"
    if let Some(type_val) = obj.get("type").cloned() {
        if let Value::Array(arr) = type_val {
            let first = arr
                .iter()
                .find(|v| v.as_str() != Some("null"))
                .cloned()
                .unwrap_or(json!("string"));
            obj.insert("type".to_string(), first);
        }
    }

    // Recurse into properties
    if let Some(Value::Object(props)) = obj.get_mut("properties") {
        for prop in props.values_mut() {
            sanitize_schema(prop);
            // Add default type for properties missing one
            if let Some(prop_obj) = prop.as_object_mut() {
                if !prop_obj.contains_key("type")
                    && !prop_obj.contains_key("$ref")
                    && !prop_obj.contains_key("enum")
                {
                    prop_obj.insert("type".to_string(), json!("string"));
                }
            }
        }
    }

    // Recurse into array items
    if let Some(items) = obj.get_mut("items") {
        sanitize_schema(items);
    }
}
